### ISSUE TITLE
Service generating 500s on unexpected json POSTs

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/rbe-token-server#12]
Errors look like:
```
{
 insertId: "5d768351000b700cb0badc78"  
 labels: {…}  
 logName: "projects/pants-remoting-beta/logs/stderr"  
 receiveTimestamp: "2019-09-09T16:52:34.083739273Z"  
 resource: {…}  
 textPayload: "Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/src/server.py", line 19, in generate_token
    travis_job = TravisJob.get_from_api(job_id=int(flask.request.get_json()["travis_job_id"]))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'"  
 timestamp: "2019-09-09T16:52:33.749580Z"  
}
```
The code here shows we must be getting `"travis_job_id": null` in our json payload.
https://github.com/pantsbuild/rbe-token-server/blob/869ba6347df8c784579466e99c1e4293936a3fda/src/server.py#L19

**Comment by jsirois** [comment]
In turn this means TRAVIS_JOB_ID is not set in the travis environment:
https://github.com/pantsbuild/pants/blob/54d0d4e5874eae9df0b938f5ea8bf15265d14db3/build-support/bin/get_rbe_token.py#L14

**Comment by Eric-Arellano** [comment]
This doesn’t seem unexpected to me. Is the unexpected thing returning the wrong code rather than a code to indicate a bad request?


What is the motivating use case for this?

**Comment by jsirois** [comment]
> This doesn’t seem unexpected to me. Is the unexpected thing returning the wrong code rather than a code to indicate a bad request?

The unexpected thing is travis not populating the `TRAVIS_JOB_ID` env var (https://docs.travis-ci.com/user/environment-variables/#default-environment-variables). It appears this was an intermittent outage though.

The motivation was failing shards in Pants CI - 500 due to the stack trace above during token gen.

**Comment by jsirois** [comment]
OK, https://github.com/pantsbuild/pants/pull/8266 proved this was user error or TravisCI flaking on populating the env var. Since user error was more likely, I looked at my PR and found an unexpected bug that was nuking env vars en-masse.
